Repository ovh/terraform-provider-ovh, pull requests merged in 2018-10, with the labels that each got.

#58 r/ovh_iploadbalancing_tcp_frontend: new resource
  ovh/helpers.go
  ovh/provider.go
  ovh/resource_ovh_iploadbalancing_tcp_frontend.go
  ovh/resource_ovh_iploadbalancing_tcp_frontend_test.go
  ovh/resource_ovh_publiccloud_private_network.go
  website/docs/r/iploadbalancing_tcp_frontend.markdown
  website/ovh.erb
Labels: size/XL

#61 Add OVH US api endpoint
  ovh/config.go
Labels: size/XS

#60 adds loadbalancer refresh
  ovh/provider.go
  ovh/resource_ovh_iploadbalancing_refresh.go
  website/docs/r/iploadbalancing_refresh.markdown
Labels: size/L

#62 r/iplb_frontend: fix default farm id issue
  ovh/resource_ovh_iploadbalancing_tcp_frontend.go
  ovh/resource_ovh_iploadbalancing_tcp_frontend_test.go
Labels: size/XS
