Repository ovh/terraform-provider-ovh, pull requests merged in 2019-11, with the labels that each got.

#83 Added HTTP farm, servers and frontend resources
  ovh/provider.go
  ovh/resource_ovh_iploadbalancing_http_farm.go
  ovh/resource_ovh_iploadbalancing_http_farm_server.go
  ovh/resource_ovh_iploadbalancing_http_farm_server_test.go
  ovh/resource_ovh_iploadbalancing_http_farm_test.go
  ovh/resource_ovh_iploadbalancing_http_frontend.go
  website/docs/r/iploadbalancing_http_farm.markdown
  website/docs/r/iploadbalancing_http_farm_server.markdown
  website/docs/r/iploadbalancing_http_frontend.markdown
  website/ovh.erb
Labels: documentation, new-resource, size/XXL

#96 Add "ovh_iploadbalancing_refresh" to the website sidebar
  website/ovh.erb
Labels: documentation, size/XS

#97 Correct variable escaping in ovh_iploadbalancing_http_route example
  website/docs/r/iploadbalancing_http_route.markdown
Labels: documentation, size/XS

#94 Split PreCheck for acceptance tests
  go.sum
  ovh/data_source_ovh_domain_zone_test.go
  ovh/data_source_ovh_iploadbalancing_test.go
  ovh/data_source_ovh_me_paymentmean_bankaccount_test.go
  ovh/data_source_ovh_me_paymentmean_creditcard_test.go
  ovh/data_source_ovh_publiccloud_region_test.go
  ovh/data_source_ovh_publiccloud_regions_test.go
  ovh/provider_test.go
  ovh/resource_ovh_domain_zone_record_test.go
  ovh/resource_ovh_domain_zone_redirection_test.go
  ovh/resource_ovh_ip_reverse_test.go
  ovh/resource_ovh_iploadbalancing_http_farm_server_test.go
  ovh/resource_ovh_iploadbalancing_http_farm_test.go
  ovh/resource_ovh_iploadbalancing_http_route_rule_test.go
  ovh/resource_ovh_iploadbalancing_http_route_test.go
  ovh/resource_ovh_iploadbalancing_tcp_farm_server_test.go
  ovh/resource_ovh_iploadbalancing_tcp_frontend_test.go
  ovh/resource_ovh_publiccloud_private_network_subnet_test.go
  ovh/resource_ovh_publiccloud_private_network_test.go
  ovh/resource_ovh_publiccloud_user_test.go
  ovh/resource_ovh_vrack_publiccloud_attachment_test.go
Labels: size/L

#99 r/ip_reverse: add sweeper
  ovh/resource_ovh_ip_reverse_test.go
Labels: size/S

#102 r/ip_reverse: fix sweeper name
  ovh/resource_ovh_ip_reverse_test.go
Labels: size/XS

#104 bump travis setup to xenial + go 1.13.x
  .travis.yml
Labels: size/XS

#106 testing: skip acc tests if required env var not present
  ovh/provider_test.go
  ovh/resource_ovh_iploadbalancing_tcp_farm_test.go
Labels: size/S

#93 Add SSH Key support
  go.sum
  ovh/data_source_ovh_me_ssh_key.go
  ovh/data_source_ovh_me_ssh_key_test.go
  ovh/data_source_ovh_me_ssh_keys.go
  ovh/data_source_ovh_me_ssh_keys_test.go
  ovh/import_me_ssh_key_test.go
  ovh/provider.go
  ovh/resource_ovh_me_ssh_key.go
  ovh/resource_ovh_me_ssh_key_test.go
  ovh/types.go
  website/docs/d/me_ssh_key.markdown
  website/docs/d/me_ssh_keys.markdown
  website/docs/r/me_ssh_key.html.markdown
  website/ovh.erb
Labels: documentation, new-resource, size/XL

#109 handle record id bigger than 32bits
  ovh/resource_ovh_domain_zone_record.go
  ovh/resource_ovh_domain_zone_record_test.go
Labels: size/XS
