Repository ovh/terraform-provider-ovh, pull requests merged in 2019-03, with the labels that each got.

#77 Fixdomaintestacc
  go.mod
  go.sum
  ovh/config.go
  ovh/resource_ovh_domain_zone_record.go
  ovh/resource_ovh_domain_zone_record_test.go
  ovh/resource_ovh_domain_zone_redirection.go
  ovh/resource_ovh_domain_zone_redirection_test.go
  vendor/github.com/hashicorp/terraform/helper/acctest/acctest.go
  vendor/github.com/hashicorp/terraform/helper/acctest/random.go
  vendor/github.com/hashicorp/terraform/helper/acctest/remotetests.go
  vendor/golang.org/x/crypto/curve25519/const_amd64.h
  vendor/golang.org/x/crypto/curve25519/const_amd64.s
  vendor/golang.org/x/crypto/curve25519/cswap_amd64.s
  vendor/golang.org/x/crypto/curve25519/curve25519.go
  vendor/golang.org/x/crypto/curve25519/doc.go
  vendor/golang.org/x/crypto/curve25519/freeze_amd64.s
  vendor/golang.org/x/crypto/curve25519/ladderstep_amd64.s
  vendor/golang.org/x/crypto/curve25519/mont25519_amd64.go
  vendor/golang.org/x/crypto/curve25519/mul_amd64.s
  vendor/golang.org/x/crypto/curve25519/square_amd64.s
  vendor/golang.org/x/crypto/ed25519/ed25519.go
  vendor/golang.org/x/crypto/ed25519/internal/edwards25519/const.go
  vendor/golang.org/x/crypto/ed25519/internal/edwards25519/edwards25519.go
  vendor/golang.org/x/crypto/internal/chacha20/chacha_generic.go
  vendor/golang.org/x/crypto/poly1305/poly1305.go
  vendor/golang.org/x/crypto/poly1305/sum_amd64.go
  vendor/golang.org/x/crypto/poly1305/sum_amd64.s
  vendor/golang.org/x/crypto/poly1305/sum_arm.go
  vendor/golang.org/x/crypto/poly1305/sum_arm.s
  vendor/golang.org/x/crypto/poly1305/sum_ref.go
  vendor/golang.org/x/crypto/ssh/buffer.go
  vendor/golang.org/x/crypto/ssh/certs.go
  vendor/golang.org/x/crypto/ssh/channel.go
  vendor/golang.org/x/crypto/ssh/cipher.go
  vendor/golang.org/x/crypto/ssh/client.go
  vendor/golang.org/x/crypto/ssh/client_auth.go
  vendor/golang.org/x/crypto/ssh/common.go
  vendor/golang.org/x/crypto/ssh/connection.go
  vendor/golang.org/x/crypto/ssh/doc.go
  vendor/golang.org/x/crypto/ssh/handshake.go
  vendor/golang.org/x/crypto/ssh/kex.go
  vendor/golang.org/x/crypto/ssh/keys.go
  vendor/golang.org/x/crypto/ssh/mac.go
  vendor/golang.org/x/crypto/ssh/messages.go
  vendor/golang.org/x/crypto/ssh/mux.go
  vendor/golang.org/x/crypto/ssh/server.go
  vendor/golang.org/x/crypto/ssh/session.go
  vendor/golang.org/x/crypto/ssh/streamlocal.go
  vendor/golang.org/x/crypto/ssh/tcpip.go
  vendor/golang.org/x/crypto/ssh/transport.go
  vendor/modules.txt
Labels: dependencies, size/XXL

#78 docs: Fix casing, typos, highlighting and names
  website/docs/d/cloud_region.html.markdown
  website/docs/d/cloud_regions.html.markdown
  website/docs/d/domain_zone.html.markdown
  website/docs/d/iploadbalancing.html.markdown
  website/docs/d/me_paymentmean_bankaccount.markdown
  website/docs/d/me_paymentmean_creditcard.markdown
  website/docs/d/publiccloud_region.html.markdown
  website/docs/d/publiccloud_regions.html.markdown
  website/docs/index.html.markdown
  website/docs/r/cloud_network_private.html.markdown
  website/docs/r/iploadbalancing_http_route.markdown
  website/docs/r/iploadbalancing_tcp_farm.markdown
  website/docs/r/publiccloud_private_network.html.markdown
  website/ovh.erb
Labels: documentation, size/M

#75 0.12: fix element issue
  ovh/data_source_ovh_publiccloud_region_test.go
  ovh/resource_ovh_publiccloud_private_network_subnet_test.go
  ovh/resource_ovh_publiccloud_private_network_test.go
Labels: size/XS

#79 docs: Make deprecations more visible
  website/docs/d/publiccloud_region.html.markdown
  website/docs/d/publiccloud_regions.html.markdown
  website/docs/r/publiccloud_private_network.html.markdown
  website/docs/r/publiccloud_private_network_subnet.html.markdown
  website/docs/r/publiccloud_user.html.markdown
  website/docs/r/vrack_publiccloud_attachment.html.markdown
Labels: documentation, size/XS

#80 docs: Enable syntax highlighting of examples
  website/docs/index.html.markdown
  website/docs/r/cloud_network_private.html.markdown
  website/docs/r/cloud_network_private_subnet.html.markdown
  website/docs/r/cloud_user.html.markdown
  website/docs/r/iploadbalancing_refresh.markdown
  website/docs/r/iploadbalancing_tcp_farm.markdown
  website/docs/r/iploadbalancing_tcp_farm_server.markdown
  website/docs/r/iploadbalancing_tcp_frontend.markdown
  website/docs/r/ovh_domain_zone_record.html.markdown
  website/docs/r/publiccloud_private_network.html.markdown
  website/docs/r/publiccloud_private_network_subnet.html.markdown
  website/docs/r/publiccloud_user.html.markdown
  website/docs/r/vrack_cloudproject.markdown
  website/docs/r/vrack_publiccloud_attachment.html.markdown
Labels: documentation, size/S

#81 Deprecate publiccloud data sources & resources
  ovh/provider.go
Labels: size/S

#82 provider: Make homedir detection more robust
  go.mod
  ovh/provider.go
Labels: enhancement, size/S
