Repository ovh/terraform-provider-ovh, pull requests merged in 2020-08, with the labels that each got.

#151 Fix/cloud user
  CHANGELOG.md
  ovh/helpers.go
  ovh/resource_ovh_cloud_user.go
  ovh/resource_ovh_cloud_user_test.go
  ovh/types_cloud.go
  website/docs/r/cloud_user.html.markdown
Labels: documentation, size/XL

#150 Feat/dedicated ceph
  ovh/data_source_ovh_dedicated_ceph.go
  ovh/data_source_ovh_dedicated_ceph_test.go
  ovh/helpers.go
  ovh/provider.go
  ovh/provider_test.go
  ovh/resource_ovh_dedicated_ceph_acl.go
  ovh/resource_ovh_dedicated_ceph_acl_test.go
  ovh/types_dedicated_ceph.go
  website/docs/d/dedicated_ceph.html.markdown
  website/docs/r/dedicated_ceph_acl.markdown
  website/ovh.erb
Labels: documentation, size/XL

#155 r/iplb_*_frontend: fix allowed sources/ipfo updates
  ovh/resource_ovh_iploadbalancing_http_frontend.go
  ovh/resource_ovh_iploadbalancing_http_frontend_test.go
  ovh/resource_ovh_iploadbalancing_tcp_frontend.go
  ovh/resource_ovh_iploadbalancing_tcp_frontend_test.go
  ovh/types_iploadbalancing.go
Labels: size/XL

#156 Update CHANGELOG
  CHANGELOG.md
Labels: size/XS
