Repository ovh/terraform-provider-ovh, pull requests merged in 2020-04, with the labels that each got.

#142 Fix sweepers on iploadbalancing_vrack_network
  ovh/resource_ovh_cloud_network_private_test.go
  ovh/resource_ovh_iploadbalancing_tcp_frontend_test.go
  ovh/resource_ovh_iploadbalancing_vrack_network_test.go
  ovh/resource_ovh_vrack_cloudproject_test.go
Labels: size/M

#140 feat(iploadbalancing): Add iploadbalancing importers
  ovh/import_iploadbalancing_http_farm_server_test.go
  ovh/import_iploadbalancing_http_farm_test.go
  ovh/import_iploadbalancing_http_frontend_test.go
  ovh/import_iploadbalancing_http_route_rule_test.go
  ovh/import_iploadbalancing_http_route_test.go
  ovh/import_iploadbalancing_tcp_farm_server_test.go
  ovh/import_iploadbalancing_tcp_farm_test.go
  ovh/import_iploadbalancing_tcp_frontend_test.go
  ovh/resource_ovh_iploadbalancing_http_farm.go
  ovh/resource_ovh_iploadbalancing_http_farm_server.go
  ovh/resource_ovh_iploadbalancing_http_farm_test.go
  ovh/resource_ovh_iploadbalancing_http_frontend.go
  ovh/resource_ovh_iploadbalancing_http_route.go
  ovh/resource_ovh_iploadbalancing_http_route_rule.go
  ovh/resource_ovh_iploadbalancing_tcp_farm.go
  ovh/resource_ovh_iploadbalancing_tcp_farm_server.go
  ovh/resource_ovh_iploadbalancing_tcp_farm_test.go
  ovh/resource_ovh_iploadbalancing_tcp_frontend.go
Labels: size/XL

#141 feat: add me/ipxeScript datasources and resource
  ovh/data_source_ovh_me_ipxe_script.go
  ovh/data_source_ovh_me_ipxe_script_test.go
  ovh/data_source_ovh_me_ipxe_scripts.go
  ovh/data_source_ovh_me_ipxe_scripts_test.go
  ovh/import_me_ipxe_script_test.go
  ovh/provider.go
  ovh/resource_ovh_me_ipxe_script.go
  ovh/resource_ovh_me_ipxe_script_test.go
  ovh/types.go
  ovh/types_me.go
  website/docs/d/me_ipxe_script.html.markdown
  website/docs/d/me_ipxe_scripts.html.markdown
  website/docs/r/me_ipxe_script.html.markdown
  website/ovh.erb
Labels: documentation, size/XL
