Repository ovh/terraform-provider-ovh, pull requests merged in 2020-01, with the labels that each got.

#117 Feat/r/dedicated server install task
  ovh/dedicated_server_task.go
  ovh/provider.go
  ovh/resource_ovh_dedicated_server_install_task.go
  ovh/resource_ovh_dedicated_server_install_task_test.go
  ovh/resource_ovh_iploadbalancing_http_farm_server_test.go
  ovh/resource_ovh_iploadbalancing_tcp_farm_server_test.go
  ovh/types_dedicated_server.go
  website/docs/r/dedicated_server_install_task.html.markdown
  website/ovh.erb
Labels: documentation, size/XL

#122 docs: fix docs various typos
  website/docs/d/me_installation_template.html.markdown
  website/docs/r/dedicated_server_reboot_task.html.markdown
  website/docs/r/dedicated_server_update.html.markdown
  website/docs/r/me_installation_template.html.markdown
  website/ovh.erb
Labels: documentation, size/XL

#123 Update CHANGELOG/README
  CHANGELOG.md
  README.md
Labels: size/M

#124 Fix/importsubnet
  ovh/data_source_ovh_cloud_region.go
  ovh/data_source_ovh_cloud_region_test.go
  ovh/data_source_ovh_cloud_regions.go
  ovh/data_source_ovh_cloud_regions_test.go
  ovh/import_cloud_network_private_subnet_test.go
  ovh/provider.go
  ovh/provider_test.go
  ovh/resource_ovh_cloud_network_private.go
  ovh/resource_ovh_cloud_network_private_subnet.go
  ovh/resource_ovh_cloud_network_private_subnet_test.go
  ovh/resource_ovh_cloud_network_private_test.go
  ovh/resource_ovh_cloud_user.go
  ovh/resource_ovh_cloud_user_test.go
  ovh/resource_ovh_iploadbalancing_http_farm_server.go
  ovh/resource_ovh_iploadbalancing_http_farm_server_test.go
  ovh/resource_ovh_iploadbalancing_tcp_farm_server.go
  ovh/resource_ovh_iploadbalancing_tcp_farm_server_test.go
  ovh/resource_ovh_vrack_cloudproject_test.go
  ovh/types.go
  ovh/types_cloud.go
Labels: size/XL

#125 Update CHANGELOG
  CHANGELOG.md
Labels: size/XS

#127 Iplb/vrack support
  ovh/data_source_ovh_iploadbalancing.go
  ovh/data_source_ovh_iploadbalancing_vrack_network.go
  ovh/data_source_ovh_iploadbalancing_vrack_network_test.go
  ovh/data_source_ovh_iploadbalancing_vrack_networks.go
  ovh/data_source_ovh_iploadbalancing_vrack_networks_test.go
  ovh/import_iploadbalancing_vrack_network_test.go
  ovh/import_vrack_ip_loadbalancing_test.go
  ovh/provider.go
  ovh/resource_ovh_iploadbalancing_http_farm.go
  ovh/resource_ovh_iploadbalancing_http_farm_server.go
  ovh/resource_ovh_iploadbalancing_http_frontend.go
  ovh/resource_ovh_iploadbalancing_http_route.go
  ovh/resource_ovh_iploadbalancing_http_route_rule.go
  ovh/resource_ovh_iploadbalancing_refresh.go
  ovh/resource_ovh_iploadbalancing_tcp_farm.go
  ovh/resource_ovh_iploadbalancing_tcp_farm_server.go
  ovh/resource_ovh_iploadbalancing_tcp_frontend.go
  ovh/resource_ovh_iploadbalancing_vrack_network.go
  ovh/resource_ovh_iploadbalancing_vrack_network_test.go
  ovh/resource_ovh_vrack_dedicated_server_test.go
  ovh/resource_ovh_vrack_ip_loadbalancing.go
  ovh/resource_ovh_vrack_ip_loadbalancing_test.go
  ovh/types_iploadbalancing.go
  ovh/types_vrack.go
  website/docs/d/iploadbalancing_vrack_network.html.markdown
  website/docs/d/iploadbalancing_vrack_networks.html.markdown
  website/docs/r/iploadbalancing_vrack_network.html.markdown
  website/docs/r/vrack_iploadbalancing.html.markdown
  website/ovh.erb
Labels: documentation, size/XXL

#129 Fix/iplb vrack network update
  CHANGELOG.md
  ovh/data_source_ovh_iploadbalancing_vrack_network_test.go
  ovh/resource_ovh_iploadbalancing_vrack_network.go
  ovh/resource_ovh_iploadbalancing_vrack_network_test.go
Labels: size/M

#128 Update CHANGELOG.md
  CHANGELOG.md
Labels: size/XS

#130 Update CHANGELOG.md
  CHANGELOG.md
Labels: size/XS

#133 add cookie to http farm stickiness
  ovh/resource_ovh_iploadbalancing_http_farm.go
  website/docs/r/iploadbalancing_http_farm.markdown
Labels: documentation, size/XS
