Repository ovh/terraform-provider-ovh, pull requests merged in 2022-09, with the labels that each got.

#294 Add ovh_cloud_project_user_s3_policy resource
  ovh/data_cloud_project_user.go
  ovh/data_cloud_project_user_s3_policy.go
  ovh/data_cloud_project_user_s3_policy_test.go
  ovh/data_cloud_project_user_test.go
  ovh/data_cloud_project_users.go
  ovh/data_cloud_project_users_test.go
  ovh/provider.go
  ovh/resource_cloud_project_user_s3_policy.go
  ovh/resource_cloud_project_user_s3_policy_test.go
  website/docs/d/cloud_project_user.html.markdown
  website/docs/d/cloud_project_user_s3_credential.html.markdown
  website/docs/d/cloud_project_user_s3_policy.html.markdown
  website/docs/d/cloud_project_users.html.markdown
  website/docs/r/cloud_project_user_s3_policy.html.markdown
  website/ovh.erb
Labels: v0.20

#298 fix: typo in kafka user access doc
  website/docs/d/cloud_project_database_kafka_user_access.html.markdown
Labels: v0.20

#299 fix: typos and imports
  website/docs/d/cloud_project_database.html.markdown
  website/docs/r/cloud_project_containerregistry_user.html.markdown
  website/docs/r/cloud_project_database.html.markdown
  website/docs/r/cloud_project_database_ip_restriction.html.markdown
  website/docs/r/cloud_project_database_kafka_acl.html.markdown
  website/docs/r/cloud_project_database_kafka_topic.html.markdown
  website/docs/r/cloud_project_database_mongodb_user.html.markdown
  website/docs/r/cloud_project_database_opensearch_pattern.html.markdown
  website/docs/r/cloud_project_database_opensearch_user.html.markdown
  website/docs/r/cloud_project_database_postgresql_user.html.markdown
  website/docs/r/cloud_project_database_redis_user.html.markdown
  website/docs/r/cloud_project_database_user.html.markdown
  website/docs/r/cloud_project_user_s3_credential.html.markdown
  website/docs/r/cloud_project_user_s3_policy.html.markdown
Labels: 0.20.1

#303 Customizable Timeout for cloud Databases resources
  ovh/resource_cloud_project_database.go
  ovh/resource_cloud_project_database_ip_restriction.go
  ovh/resource_cloud_project_database_kafka_acl.go
  ovh/resource_cloud_project_database_kafka_topic.go
  ovh/resource_cloud_project_database_mongodb_user.go
  ovh/resource_cloud_project_database_opensearch_pattern.go
  ovh/resource_cloud_project_database_opensearch_user.go
  ovh/resource_cloud_project_database_postgresql_user.go
  ovh/resource_cloud_project_database_redis_user.go
  ovh/resource_cloud_project_database_user.go
  ovh/types_cloud_project_database.go
  website/docs/r/cloud_project_database.html.markdown
  website/docs/r/cloud_project_database_ip_restriction.html.markdown
  website/docs/r/cloud_project_database_kafka_acl.html.markdown
  website/docs/r/cloud_project_database_kafka_topic.html.markdown
  website/docs/r/cloud_project_database_mongodb_user.html.markdown
  website/docs/r/cloud_project_database_opensearch_pattern.html.markdown
  website/docs/r/cloud_project_database_opensearch_user.html.markdown
  website/docs/r/cloud_project_database_postgresql_user.html.markdown
  website/docs/r/cloud_project_database_redis_user.html.markdown
  website/docs/r/cloud_project_database_user.html.markdown
Labels: 0.20.1

#302 fix: iplb frontend default values
  ovh/helpers/helpers.go
Labels: 0.20.1

#304 Kube/feat/customization apiserver admissionplugins
  ovh/data_cloud_project_kube.go
  ovh/helpers/helpers.go
  ovh/resource_cloud_project_kube.go
  ovh/resource_cloud_project_kube_test.go
  ovh/types_cloud_project_kube.go
  ovh/types_cloud_project_kube_nodepool.go
  website/docs/r/cloud_project_kube.html.markdown
Labels: 0.20.1

#305 fix: schema have been modified so tolist is now required
  ovh/resource_cloud_project_kube_test.go
Labels: 0.20.1

#306 fix missing doc for data kube nested object customization
  website/docs/d/cloud_project_kube.html.markdown
Labels: 0.22.0

#311 feat: add kube node pool and ip restrictions import in doc
  website/docs/r/cloud_project_kube.html.markdown
  website/docs/r/cloud_project_kube_iprestrictions.html.markdown
  website/docs/r/cloud_project_kube_nodepool.html.markdown
Labels: 0.22.0

#310 fix: TestAccCloudProjectKubeVRack acceptance test
  ovh/provider_test.go
  ovh/resource_cloud_project_kube_test.go
Labels: 0.22.0

#315 add kubeconfig in state when import
  ovh/resource_cloud_project_kube.go
  ovh/resource_cloud_project_kube_helpers.go
Labels: 0.22.0

#317 improve cloud_project_database doc
  ovh/resource_cloud_project_database.go
  website/docs/d/cloud_project_database.html.markdown
  website/docs/r/cloud_project_database.html.markdown
Labels: 0.22.0
