Repository ovh/terraform-provider-ovh, pull requests merged in 2023-01, with the labels that each got.

#351 Add resource dedicated_server_networking
  .gitignore
  ovh/provider.go
  ovh/resource_dedicated_server_networking.go
  ovh/resource_dedicated_server_networking_test.go
  ovh/types_dedicated_server_networking.go
  website/docs/index.html.markdown
  website/docs/r/ovh_dedicated_server_networking.html.markdown
Labels: 0.26.0

#346 Fix import of ovh_ip_reverse resources with IPv6
  ovh/resource_ip_reverse.go
  website/docs/r/ip_reverse.html.markdown
Labels: 0.26.0

#355 Doc kube: reorder and fix the list of attributes
  website/docs/r/cloud_project_kube.html.markdown
Labels: 0.26.0

#356 Add support for HTTP header on resource_iploadbalancing_http_frontend
  ovh/resource_iploadbalancing_http_frontend.go
  ovh/resource_iploadbalancing_http_frontend_test.go
  ovh/types_iploadbalancing.go
  website/docs/r/iploadbalancing_http_frontend.html.markdown
Labels: 0.26.0

#354 fix node pool read template
  ovh/data_cloud_project_kube_nodepool.go
  ovh/resource_cloud_project_kube_nodepool.go
  ovh/types_cloud_project_kube_nodepool.go
Labels: 0.26.0

#357 fix 3 issue for nodepool deserialization
  ovh/data_cloud_project_kube_nodepool.go
  ovh/resource_cloud_project_kube_nodepool.go
  ovh/types_cloud_project_kube_nodepool.go
Labels: 0.26.0

#361 Clarify cloud project import
  website/docs/r/cloud_project.html.markdown
Labels: Type: Documentation, 0.27.0

#363 update expire time format to RFC3339 constant to avoid local time issues
  ovh/data_order_cart.go
Labels: 0.27.0
